### ISSUE TITLE
新版不能手动跟自动切换代理模式

### ISSUE THREAD

**Issue by ximenlangzige** [FelisCatus/SwitchyOmega#1003]
WINDOWS XP 浏览器版本 47.0.2526.111中使用中自动更新到Proxy SwitchyOmega 2.4.0不能手动跟自动切换代理模式！换回2.3就可以用 但是它会自动更新啊 ，2.3可以用，但是 不知道什么时候就会自动更新2.4，一直都在系统代理上！

SwitchyOmega 2.4.0
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
```
[42] Unhandled rejection:
 Error: Invalid value for argument 1. Property 'imageData': Value does not match any valid type choices.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:117:3)
    at Object.<anonymous> (extensions::binding:374:30)
    at ChromeTabs.setIcon (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5686:35)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5657:15
From previous event:
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5655:39)
    at ChromeTabs.onUpdated (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5627:17)
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5593:26)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
```

**Comment by celeron533** [comment]
有好几个人反映这个问题，不过奇怪的是，我公司win7和家里的win10都没有问题。两者皆是chrome56。

**Comment by ximenlangzige** [comment]
真的是这种情况！就是点击某个代理选项后弹出菜单并不会选中二一直在系统代理上或者选中后能够改变选项，菜单不消隐，颜色不改变！希望能够修复！谢谢！

2017-02-28 22:50 GMT+08:00 Allen Zhu <notifications@github.com>:

**Comment by zxysm** [comment]
我也遇到图标一直是蓝色的问题了，手动切换并不起作用

**Comment by r03r03** [comment]
昨天就是这个情况，手动卸载，安装了旧版本，可以正常使用。结果今天早上又自动更新到2.4版本，又不行了。
[OmegaLog_1488326483656.txt](https://github.com/FelisCatus/SwitchyOmega/files/809330/OmegaLog_1488326483656.txt)

**Comment by FelisCatus** [comment]
这次坑了， Chrome 在某个版本改了图标的大小，改成了 16x16 ，但之前的版本还是只认 19x19. 这样的话低版本就会有一个兼容问题。我正在想办法修复。

**Comment by FelisCatus** [comment]
让我试试看同时兼容高版本和低版本的 Chrome. 给我一点时间，应该能很快修复。

**Comment by FelisCatus** [comment]
我找到了一个旧版的 Chrome ，测试中。

**Comment by FelisCatus** [comment]
非常尴尬……目前的结果显示，旧版的 Chrome 只要有不是 19x19 或者 38x38 的图标就会报错。这样的话我就没办法提供新版的 32x32 图标了…… Chrome 为什么要这样对开发者……唉。

**Comment by FelisCatus** [comment]
用比较粗暴的方式解决了……现在各种大小的图标都会绘制，如果 Chrome 不接受图标的话就重试只有 `19x19` 和 `38x38` 的，应该就能通过了……以后再慢慢优化，现在先能用了再说……
管它呢，就这样发布吧！2.4.1 已提交审核。

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。

**Comment by Arthur2012** [comment]
@FelisCatus v2.4.1可以正常切换代理了。
还有个小问题，不知道其他人是否也碰到，就是鼠标悬停的提示一直是“正在加载......”。
浏览器是360浏览器8.1.1.248，Chrome内核模式，内核版本45.0.2454.101。
![image](https://cloud.githubusercontent.com/assets/25565376/23448630/03d629ec-fe8d-11e6-82ab-15200e40ff5c.png)

**Comment by FelisCatus** [comment]
@Arthur2012 不知道 360 又搞了什么不兼容的玩意……总之试试看右键点那个图标，然后点反馈问题吧。

**Comment by ximenlangzige** [comment]
谢谢更新插件!辛苦了！

2017-03-01 15:11 GMT+08:00 Felis Catus <notifications@github.com>:

**Comment by FelisCatus** [comment]
@Arthur2012 刚知道 360 右键菜单显示不出反馈问题选项……好吧，抱歉。关于增加版本显示和反馈问题的其他渠道，请参见 #1008.

然后关于正在加载，请问这个问题是一直就有，还是最近更新2.4.0之后才出现？如果是一直就有，会不会是 360 根本就不让动态修改悬停提示？

**Comment by mlkt** [comment]
360是能动态修改悬停提示的

**Comment by FelisCatus** [comment]
于是我感觉这就很奇怪了…… @Arthur2012 的浏览器版本是最新的吗？更新下或者装开发版试试看？
@mlkt 那边也有这样的问题吗？版本多少？

如果真是同样的代码 Chrome 能改悬停提示，但 360 不能改，我就不知道该怎么办了。除非我也装个 360 浏览器……但是我这里是 Linux 系统哎……

**Comment by FelisCatus** [comment]
2.4.2 已经添加“关于”页面，可以在选项页面点击左上角 SwitchyOmega 字样查看。页面上有反馈问题按钮和版本号。

悬停提示的问题我还是没有头绪，估计要等好心人帮忙分析下了……

**Comment by ximenlangzige** [comment]
想帮忙 但是有心无力啊

在 2017年3月12日 上午11:30，Felis Catus <notifications@github.com>写道：
