### ISSUE TITLE
It cannot be switched from 'GoAgent' proxy accessing to 'direct' accessing via 'Quick Switch' feature

### ISSUE THREAD

**Issue by KimXiao** [FelisCatus/SwitchyOmega#1004]
It cannot be switched from 'GoAgent' proxy accessing to 'direct' accessing via 'Quick Switch' feature, and the icon is still highlighted.

Yesterday I met the same issue, and fixed it by delete it in Extension Manager, and reinstall the package from the URL:  https://github.com/FelisCatus/SwitchyOmega/releases/download/v2.3.21/SwitchyOmega.crx.

SwitchyOmega 2.4.0
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
```
[6] Unhandled rejection:
 Error: Invalid value for argument 1. Property 'imageData': Value does not match any valid type choices.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:117:3)
    at Object.<anonymous> (extensions::binding:374:30)
    at ChromeTabs.setIcon (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5686:35)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5657:15
From previous event:
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5655:39)
    at ChromeTabs.onUpdated (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5627:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5608:26
    at Array.forEach (native)
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5605:21)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
```

**Comment by FelisCatus** [comment]
See #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。
