### ISSUE TITLE
图标颜色和形状一直都不改变

### ISSUE THREAD

**Issue by dslztx** [FelisCatus/SwitchyOmega#1007]
图标一直处于蓝色状态，不管选择什么模式，图标的颜色和形状都不改变，而且过段时间自动转为“系统代理”模式

SwitchyOmega 2.4.0
Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
```
Error: Invalid value for argument 1. Property 'imageData': Value does not match any valid type choices.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:117:3)
    at Object.<anonymous> (extensions::binding:339:30)
    at ChromeTabs.setIcon (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5691:35)
    at ChromeTabs.resetAll (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5616:17)
    at ChromeOptions.options.currentProfileChanged (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:341:17)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9542:10)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9020:22
From previous event:
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9015:23)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9172:24
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。

**Comment by dslztx** [comment]
谢谢
