### ISSUE TITLE
2.4.4不方便！！没有了快速添加规则的选项？

### ISSUE THREAD

**Issue by nns123** [FelisCatus/SwitchyOmega#1023]
你好！2.4.4版本没有了快速添加规则的选项 十分不方便 难道选个规则都要点选项进去设置 自己写代码吗？ 非常麻烦啊 不会些代码规则的小白怎么办 百度个半天去填个规则吗？？？？？
希望改进！！！！！！ 谢谢

SwitchyOmega 2.4.4
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```
[12] Unhandled rejection:
 TypeError: Cannot read property 'tabInfo' of null
    at ChromeOptions.getPageInfo (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4934:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:392:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:391:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:378:19
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:196:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispa

**Comment by FelisCatus** [comment]
v2.4.5 已修复。
