### ISSUE TITLE
设置界面乱码

### ISSUE THREAD

**Issue by qysjames** [FelisCatus/SwitchyOmega#1027]
The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
buildFragment @ jquery.min.js:3
n.parseHTML @ jquery.min.js:4
n.fn.init @ jquery.min.js:2
n @ jquery.min.js:2
(anonymous) @ spectrum.js:76
(anonymous) @ spectrum.js:78
(anonymous) @ spectrum.js:16
(anonymous) @ spectrum.js:18
angular.min.js:92 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:".

    at eval (<anonymous>)
    at Function.globalEval (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:2538)
    at n.fn.init.domManip (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:17203)
    at n.fn.init.append (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:14886)
    at n.fn.init.<anonymous> (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:16246)
    at n.access (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:30124)
    at n.fn.init.html (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:15917)
    at n.fn.init.e [as html] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:25:207)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular-ui-router/angular-ui-router.js:3891:18
    at J (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:54:373) <main ui-view="" class="col-lg-10 col-sm-9 col-lg-offset-2 col-sm-offset-3 angular-animate ng-scope">

**Comment by celeron533** [comment]
会不会和#940 一个原因？

**Comment by qysjames** [comment]
@celeron533 要全盘查杀吗，我用的是Cent Browser

**Comment by celeron533** [comment]
可以去 https://github.com/FelisCatus/SwitchyOmega/issues/540#issuecomment-166295033 看看文件夹下的语言定义文件是否被破坏
```
C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default\Extensions\padekgcemlokbadohgkifijomclgjgif\<version>\_locales\zh_CN
```

**Comment by qysjames** [comment]
@celeron533 语言定义文件没有损坏，那应该是感染病毒了吧

**Comment by FelisCatus** [comment]
这个应该是中毒……可以手动打开 partials 目录下的几个 HTML 文件看看里面有没有被加入 `<script>`. （正常的情况下这几个文件里不应该有 script.） 如果有的话手动删除大概可以缓解一时，不过病毒还在的话估计还会反复加入恶意脚本吧，所以杀毒吧。
