### ISSUE TITLE
[Direct] and failed to load a resource -- why?

### ISSUE THREAD

**Issue by herodan** [FelisCatus/SwitchyOmega#1063]
I'm using [Direct] with SwitchyOmega, but for some reason it reports a resource that failed to load (*.facebook.com) -- why is it reporting on a failed resource to load when it's direct (and in theory not using a proxy)?

I was able to get the error via going to facebook, and then clicking on an update from a friend on the right side bar (above chat).

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
```
[8] Unhandled rejection:
 TypeError: Cannot read property 'replace' of null
    at Object.requestFromUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:9760:27)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:108:37
From previous event:
    at ChromeTabs.actionForUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:106:26)
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5660:17)
    at ChromeTabs.onUpdated (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5632:17)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at dispatchArgs (extensions::event_bindings:244:26)
    at dispatchEvent (extensions::event_bindings:253:7)
```

**Comment by FelisCatus** [comment]
Network issues are reported but not caused by SwitchyOmega. It can be an issue with your ISP or simply Facebook itself. These failed requests are shown there to facilitate diagnostics.

SwitchyOmega has no control over the network internals and therefore it can't tell whether a request is using a proxy or not. Plus, some of the requests actually won't load without a proxy, for example company intranet resources or region-specific resources.

With that being said, please feel free to disable network monitoring in the options page if you want to silence the warnings.

**Comment by herodan** [comment]
Thanks for the response. :)
