### ISSUE TITLE
VPNs Broken !!!!

### ISSUE THREAD

**Issue by moanaa19** [FelisCatus/SwitchyOmega#1067]
none of the vpns work . and i cant install anything from the chrome store, because this version is too old. I cant install the new versions as well . Please help ASAP

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/24.0.2062.68 Safari/537.36
```
[1] Unhandled rejection:
 Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_pac.min.js:14402:15)
    at Object.module.exports.exports.compile (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_pac.min.js:14380:45)
    at chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_pac.min.js:13861:29
    at Object.module.exports.script (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_pac.min.js:13865:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_target.min.js:11259:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_target_chromium_extension.min.js:3994:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_target.min.js:11381:25)
    at chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/background.js:357:23
From previous event:
From previous event:
    at new Promise (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://dejoligghbahkfbejbffbpcbfigncall/js/omega_target_chromium_extension.min.js:3497:12)
    at Chro

**Comment by celeron533** [comment]
SwitchyOmega is just a proxy setting tool, totally different from VPN.
If you would like to install new version of Chrome, please modify your system global proxy settings (from Internet Explorer, Internet options. Assuming you are using Windows) then go to Chrome about page to let it update automatically. Then navigate to Chrome store to install new extensions.

SwitchyOmega 只是基于浏览器的代理服务器设置工具，其运行方式和原理完全和VPN不同。
如果你想要安装新版的Chrome浏览器，设置系统全局代理服务器（IE，internet选项。假设你是windows平台。）然后去chrome的关于页面，让他自动更新。然后去Chrome store安装新的扩展程序（此时依旧在系统全局代理）
