### ISSUE TITLE
000

### ISSUE THREAD

**Issue by srshd2015** [FelisCatus/SwitchyOmega#1096]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
```
[2] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:79:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
    at responseCallback (extensions::messaging:185:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:409:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:400:15
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:378:19
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:149:26)
    at messageListener (extensions::messaging:215:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (exten

**Comment by FelisCatus** [comment]
?
