### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by drodgers76** [FelisCatus/SwitchyOmega#1151]
Hi,

I have been using this extension for some time and I absolutely love it, thank you for all of your work.

There is however one thing that does but me at times.

If you close Chrome with the Proxy active, then open it again, you are faced with the 'authentication required' dialog (even if the proxy is no longer on).

Is this because the authentication comes up before chrome starts the extension? Can anything be done about this?

Kind regards,
Dave

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```
[1] Unhandled rejection:
 TypeError: Cannot read property 'replace' of null
    at Object.requestFromUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:9760:27)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:108:37
From previous event:
    at ChromeTabs.actionForUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:106:26)
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5660:17)
    at ChromeTabs.onUpdated (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5632:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5613:26
    at Array.forEach (<anonymous>)
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5610:21)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by FelisCatus** [comment]
This should be caused by authentication comes up before chrome starts the extension. As far as I know, there really isn't anyway to work around.
