### ISSUE TITLE
chrome 版本 63.0.3236.0（正式版本）canary （64 位） js 报错

### ISSUE THREAD

**Issue by mayy1980** [FelisCatus/SwitchyOmega#1238]
[OmegaLog_1507559645372.txt](https://github.com/FelisCatus/SwitchyOmega/files/1368969/OmegaLog_1507559645372.txt)

![image](https://user-images.githubusercontent.com/4936857/31343742-10c574d6-ad43-11e7-9162-15871d1653c8.png)

SwitchyOmega 2.5.4
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3236.0 Safari/537.36
```
[1] Unhandled rejection:
 TypeError: Error processing argument at index -1, conversion failure from undefined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3936:31
    at Object.clearAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3918:12)
    at ChromeOptions.applyProfileProxySettings (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4683:28)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4668:19)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9617:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9045:22
From previous event:
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9040:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8848:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:

**Comment by FelisCatus** [comment]
我很怀疑是 Chrome Dev 版那边自己改了什么了……试试看其他版本，更新的 Nightly 或者更旧的 Beta 都可以试试看。或者也可以等几天看看那边是否修复。

**Comment by celeron533** [comment]
windows7 
```Version 61.0.3163.100 (Official Build) (64-bit)```
目前没有问题

**Comment by codehz** [comment]
64.0.3264.0同样无法运行

**Comment by FelisCatus** [comment]
求更多报告之类的，错误截图或者导出日志均可。

**Comment by FelisCatus** [comment]
374d47a 已经修复。应该是调用 `Object.create` 时创建了新的对象，所以 Chrome 不接受新的对象作为 `this`. 这个行为是之前没有的，不过毕竟是没文档的东西，挂了也没话说……总之这个我认了，下次我会小心点。

v2.5.8 发布中。

**Comment by FelisCatus** [comment]
v2.5.8 已修复。
