### ISSUE TITLE
Error of SwitchyOmega

### ISSUE THREAD

**Issue by terryzhouke** [FelisCatus/SwitchyOmega#1261]
SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.102 Safari/537.36 Vivaldi/1.93.955.38
```
[3] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:144:26)
    at responseCallback (extensions::messaging:208:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:443:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:434:15
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:407:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:144:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:144:26)
    at messageListener (extensions::messaging:238:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at E

**Comment by FelisCatus** [comment]
@terryzhouke This seems to be harmless. Let me know if you experience other issues.
