### ISSUE TITLE
Lead to chromo "error profile"

### ISSUE THREAD

**Issue by TriLoo** [FelisCatus/SwitchyOmega#1383]
SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
```
[2] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at responseCallback (extensions::messaging:210:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:452:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:443:15
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:416:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::ev

**Comment by FelisCatus** [comment]
What do you want to achieve? What steps did you take? What was the expected result and the actual result?

**Comment by TriLoo** [comment]
Thanks for reply. I have solved this error. 
Actually, my configurations of SSR lead to this error, and the SwitchyOmega works good. thankyour very much .
