### ISSUE TITLE
添加临时规则时出错

### ISSUE THREAD

**Issue by debugzxcv** [FelisCatus/SwitchyOmega#1589]
### SwitchyOmega version / SwitchyOmega 版本
2.5.18

### Browser version & OS version / 浏览器名称、版本及操作系统版本

> chrome 70.0.3514.0 (Official Build) (64-bit) Windows 7 x64

### Problem description / 问题描述
添加临时规则时出错

#### Steps to reproduce issue / 重现错误所需步骤

1.
2.
3.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

<details><summary>错误日志</summary>

```
FileSaver.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
background.js:27 Options << Options#applyProfile Array(1)
background.js:27 Options << Options#updateProfile Array(1)
background.js:27 Options << Options#updateProfile Array(0)
background.js:27 Options << Options#addTempRule (2) ["github.com", "[HTTP] a"]
background.js:27 Options << Options#applyProfile ["auto switch"]
omega_target.min.js:277 [Violation] 'setTimeout' handler took 58ms
background.js:35 [1] Unhandled rejection:
 TypeError: Cannot read property 'auth' of undefined
    at ProxyAuth.module.exports.ProxyAuth.setProxies (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5211:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5349:33
From previous event:
    at SettingsProxyImpl.ProxyImpl.setProxyAuth (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5333:26)
    at SettingsProxyImpl.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5705:17)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9775:35)
    at ChromeOptions.Options.addTempRule (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10118:19)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:445:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:444:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:426:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at dispatchOnMessage (extensions::messaging:392:22)
Log.error @ background.js:35
(anonymous) @ background.js:48
CapturedTrace.fireRejectionEvent @ omega_target.min.js:814
Promise._notifyUnhandledRejection @ omega_target.min.js:1237
(anonymous) @ omega_target.min.js:267
setTimeout (async)
(anonymous) @ omega_target.min.js:266
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invokeLater @ omega_target.min.js:265
Promise._ensurePossibleRejectionHandled @ omega_target.min.js:1225
Promise._rejectUnchecked @ omega_target.min.js:3008
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
Promise._settlePromises @ omega_target.min.js:3016
(anonymous) @ omega_target.min.js:288
setTimeout (async)
schedule @ omega_target.min.js:259
Async.settlePromises @ omega_target.min.js:287
Promise._queueSettlePromises @ omega_target.min.js:2956
Promise._rejectUnchecked @ omega_target.min.js:3006
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
Promise._settlePromises @ omega_target.min.js:3016
(anonymous) @ omega_target.min.js:288
setTimeout (async)
schedule @ omega_target.min.js:259
Async.settlePromises @ omega_target.min.js:287
Promise._queueSettlePromises @ omega_target.min.js:2956
Promise._rejectUnchecked @ omega_target.min.js:3006
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
SettingsProxyImpl.applyProfile @ omega_target_chromium_extension.min.js:5705
Options.applyProfile @ omega_target.min.js:9775
Options.addTempRule @ omega_target.min.js:10118
(anonymous) @ background.js:445
tryCatcher @ omega_target.min.js:4722
Promise._settlePromiseFromHandler @ omega_target.min.js:2826
Promise._settlePromiseAt @ omega_target.min.js:2900
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
(anonymous) @ background.js:444
tryCatcher @ omega_target.min.js:4722
Promise._settlePromiseFromHandler @ omega_target.min.js:2826
Promise._settlePromiseAt @ omega_target.min.js:2900
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
(anonymous) @ background.js:426
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
messageListener @ extensions::messaging:240
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnMessage @ extensions::messaging:392
background.js:35 [2] Unhandled rejection:
 TypeError: Cannot read property 'auth' of undefined
    at ProxyAuth.module.exports.ProxyAuth.setProxies (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5211:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5349:33
From previous event:
    at SettingsProxyImpl.ProxyImpl.setProxyAuth (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5333:26)
    at SettingsProxyImpl.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5705:17)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9775:35)
    at ChromeOptions.Options.addTempRule (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10118:19)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:445:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:444:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:426:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at dispatchOnMessage (extensions::messaging:392:22)
Log.error @ background.js:35
(anonymous) @ background.js:48
CapturedTrace.fireRejectionEvent @ omega_target.min.js:814
Promise._notifyUnhandledRejection @ omega_target.min.js:1237
(anonymous) @ omega_target.min.js:267
setTimeout (async)
(anonymous) @ omega_target.min.js:266
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invokeLater @ omega_target.min.js:265
Promise._ensurePossibleRejectionHandled @ omega_target.min.js:1225
Promise._rejectUnchecked @ omega_target.min.js:3008
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._settlePromiseAt @ omega_target.min.js:2884
Promise._settlePromises @ omega_target.min.js:3016
(anonymous) @ omega_target.min.js:288
setTimeout (async)
schedule @ omega_target.min.js:259
Async.settlePromises @ omega_target.min.js:287
Promise._queueSettlePromises @ omega_target.min.js:2956
Promise._rejectUnchecked @ omega_target.min.js:3006
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
Promise._settlePromises @ omega_target.min.js:3016
(anonymous) @ omega_target.min.js:288
setTimeout (async)
schedule @ omega_target.min.js:259
Async.settlePromises @ omega_target.min.js:287
Promise._queueSettlePromises @ omega_target.min.js:2956
Promise._rejectUnchecked @ omega_target.min.js:3006
Promise._reject @ omega_target.min.js:2875
Promise._settlePromiseAt @ omega_target.min.js:2915
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
SettingsProxyImpl.applyProfile @ omega_target_chromium_extension.min.js:5705
Options.applyProfile @ omega_target.min.js:9775
Options.addTempRule @ omega_target.min.js:10118
(anonymous) @ background.js:445
tryCatcher @ omega_target.min.js:4722
Promise._settlePromiseFromHandler @ omega_target.min.js:2826
Promise._settlePromiseAt @ omega_target.min.js:2900
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
(anonymous) @ background.js:444
tryCatcher @ omega_target.min.js:4722
Promise._settlePromiseFromHandler @ omega_target.min.js:2826
Promise._settlePromiseAt @ omega_target.min.js:2900
Promise._settlePromiseAtPostResolution @ omega_target.min.js:2564
(anonymous) @ omega_target.min.js:278
setTimeout (async)
schedule @ omega_target.min.js:259
Async.invoke @ omega_target.min.js:277
Promise._then @ omega_target.min.js:2555
Promise.then @ omega_target.min.js:2432
(anonymous) @ background.js:426
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
messageListener @ extensions::messaging:240
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnMessage @ extensions::messaging:392

```
</details>

**Comment by FelisCatus** [comment]
#1593
