### ISSUE TITLE
The latest version of chrome breaks the plugin

### ISSUE THREAD

**Issue by thehandcoder** [FelisCatus/SwitchyOmega#1593]
SwitchyOmega 2.5.18
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
```
[4] Unhandled rejection:
 TypeError: Cannot read property 'auth' of undefined
    at ProxyAuth.module.exports.ProxyAuth.setProxies (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5211:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5349:33
From previous event:
    at SettingsProxyImpl.ProxyImpl.setProxyAuth (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5333:26)
    at SettingsProxyImpl.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5705:17)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9775:35)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:445:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:444:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:426:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387

**Comment by FelisCatus** [comment]
v2.5.19 已经修复。
Fixed in v2.5.19.
