### ISSUE TITLE
无法导出备份文件

### ISSUE THREAD

**Issue by Jack-ban** [FelisCatus/SwitchyOmega#1596]
我无法导出备份文件到本地，导入倒是可以的。
而且就在近几天，我发现有些网站无法代理成功。我查看了自己代理程序日志，没有发现相应的请求包被转发过来。
我尝试禁用插件，然后全局代理，发现网站可以访问，也就说代理程序没有问题，网站也没问题。
希望尽快排查！

SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
```
[8] Unhandled rejection:
 TypeError: Cannot read property 'auth' of undefined
    at ProxyAuth.module.exports.ProxyAuth.setProxies (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5211:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5349:33
From previous event:
    at SettingsProxyImpl.ProxyImpl.setProxyAuth (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5333:26)
    at SettingsProxyImpl.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5705:17)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9775:35)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:445:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:444:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:426:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispa

**Comment by 0x24bin** [comment]
我也遇到同样问题

**Comment by xmoer** [comment]
确实是缺少了文件 FileSaver.min.js

**Comment by FelisCatus** [comment]
见 #1594.
