### ISSUE TITLE
Win10+Chrome69.0.3497.100始终报错

### ISSUE THREAD

**Issue by SouWilliams** [FelisCatus/SwitchyOmega#1649]
始终提示127.0.0.1
![image](https://user-images.githubusercontent.com/6127395/46818629-49c11c80-cdb4-11e8-8f40-721d3ac8615f.png)

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
```
[1] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at responseCallback (extensions::messaging:210:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:466:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:457:15
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototy

**Comment by SouWilliams** [comment]
@AnyWAT 谢谢回复，我设置了直连。但是每次都还是要提示

**Comment by SouWilliams** [comment]
![image](https://user-images.githubusercontent.com/6127395/47057201-3538b600-d1f2-11e8-9a73-69182fdba635.png)

**Comment by SouWilliams** [comment]
是不是因为Chrome版本太高的原因，插件兼容性有问题。我现在升级到了Chrome70

**Comment by FelisCatus** [comment]
我想我知道了，应该是有某一个网站一直在请求 127.0.0.1 ，然后失败了。我倒是想知道是什么网站……不过这是网站的问题， SwitchyOmega 只是报告了这个问题而已，不需要处理的。
