### ISSUE TITLE
What should I do to deal with this problem??Thank you .

### ISSUE THREAD

**Issue by zorro0109** [FelisCatus/SwitchyOmega#173]
chrome,linux (debian)
python proxy.py
consule show 

Traceback (most recent call last):
  File "/opt/google_appengine/goagent/local/proxy.py", line 919, in <module>
    common = Common()
  File "/opt/google_appengine/goagent/local/proxy.py", line 797, in __init__
    self.LISTEN_IP            = self.CONFIG.get('listen', 'ip')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'listen'
Exception KeyError: KeyError(139715551351344,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

SwitchyOmega 2.2.11
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.45 Safari/537.36

**Comment by FelisCatus** [comment]
This is the issue tracker for SwitchyOmega, not GoAgent.
