### ISSUE TITLE
谷歌搜索结果自动跳转

### ISSUE THREAD

**Issue by StephenAnboer** [FelisCatus/SwitchyOmega#1750]
我只要打开这个插件，用谷歌搜索的时候就会自动跳转到下面这个网址，然后跳转成bing搜索的结果，不知道是为什么
https://www.search323892.xyz/search/un/?n=50&q=为什么会跳转

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
```
[1] Unhandled rejection:
 Error: Invalid options!
    at ChromeOptions.Options.parseOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9295:13)
    at ChromeOptions.Options.reset (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9312:30)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:449:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:448:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
```

**Comment by StephenAnboer** [comment]
补充一下，选择AutoProxy时候会有这个问题。Switchy就没有问题

**Comment by AnyWAT** [comment]
https://www.google.com/search?q=%E8%B0%B7%E6%AD%8C%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%B8%BAbing&oq=%E8%B0%B7%E6%AD%8C%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%B8%BAbing&aqs=chrome..69i57j69i61&sourceid=chrome&ie=UTF-8 谷歌搜索结果自动跳转为bing
![image](https://user-images.githubusercontent.com/37962734/53150419-82d38e00-35eb-11e9-8bfc-f3fdfae359de.png)

**Comment by StephenAnboer** [comment]
> https://www.google.com/search?q=%E8%B0%B7%E6%AD%8C%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%B8%BAbing&oq=%E8%B0%B7%E6%AD%8C%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%B8%BAbing&aqs=chrome..69i57j69i61&sourceid=chrome&ie=UTF-8 谷歌搜索结果自动跳转为bing
> ![image](https://user-images.githubusercontent.com/37962734/53150596-dc3bbd00-35eb-11e9-9c1a-5e8c2933af68.png)
> https://bbs.saraba1st.com/2b/thread-1722425-1-1.html
> https://iask.sina.com.cn/b/18567615.html

这些方法都没啥用，而且应该不是这个原因，因为我开smart router模式就没有问题了，或者不用插件也就没事了

**Comment by huanghe2015** [comment]
感觉应该是代理捣的鬼，或者是DNS劫持。扩展本身不会干这种事情。

**Comment by StephenAnboer** [comment]
> 感觉应该是代理捣的鬼，或者是DNS劫持。扩展本身不会干这种事情。

不知道，我已经准备重新装系统了。。。换个硬盘重装个系统，我坚信肯定就好了

**Comment by T25kevin** [comment]
浏览器的问题
