### ISSUE TITLE
swithyOmega error

### ISSUE THREAD

**Issue by shangwenqiang** [FelisCatus/SwitchyOmega#1814]
SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
```
[2] Unhandled rejection:
 TypeError: Cannot read property '-downloadInterval' of null
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10403:27
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at Object.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3117:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4144:25)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10321:34)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3403:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:179:13
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:366:4
```

**Comment by AnyWAT** [comment]
2.2.14 😱SwitchyOmega 2.5.20
