### ISSUE TITLE
安装插件后，进入插件选项，一片空白

### ISSUE THREAD

**Issue by magina74** [FelisCatus/SwitchyOmega#1887]
将 crx 文件改为 zip 文件，解压后，加载到谷歌浏览器，安装成功。但打开选项后，一片空白，没有相关页面。

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
```
[1] Unhandled rejection:
 TypeError: Illegal invocation: Function must be called on an object of type ChromeSetting
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3936:31
    at Object.clearAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3918:12)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4611:28)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9591:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9031:22
From previous event:
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9026:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8834:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4427:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:214:13
    at chrome-extension://pa

**Comment by gggccc44** [comment]
为毛要改？什么浏览器？你直接谷歌商店装不就好了，用这个的应该都有梯子吧，先浏览器设置个全局，去商店装，我360se，uc甚至火狐都直接商店装的没问题啊。除非你是用搜狗这种阉割的过份的，老实去它的商店装吧，应该只有很老的版本

**Comment by yfdyh000** [comment]
@magina74 根据网上帖子，Safari 不支持代理API。
https://github.com/feliscatus/switchyomega/issues/186
https://github.com/FelisCatus/SwitchyOmega/issues/339
