### ISSUE TITLE
没事别乱改界面和操作逻辑行不行？

### ISSUE THREAD

**Issue by xclimbing** [FelisCatus/SwitchyOmega#1889]
原来最早的Switchy界面最简洁好用，非得改成难用的Omega形式，好不容易适应了Omega形式，你们又改！越改越难用。你们大脑的干燥程度正常吗？

生命的意义在于折腾？！折腾你们自己就好了。没有多少用户愿意不断改变自己的使用习惯。这样改的意义在哪里？

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
```
[19] Unhandled rejection:
 Error: IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)
    at callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3966:19)
From previous event:
    at Object.set (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3960:12)
    at ChromeStorage.set (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5878:41)
    at ChromeOptions.Options._setOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9454:28)
    at ChromeOptions._setOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8852:57)
    at ChromeOptions.Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10197:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:449:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:448:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
```

**Comment by xclimbing** [comment]
在我看来，根本不需要改啊。原来就挺好用的。

**Comment by vicentory** [comment]
你倒是说出哪里不好用啊，纯吐槽没有意义啊，不喜欢新的可以自己去下载老版本用啊
