### ISSUE TITLE
自动清空设置

### ISSUE THREAD

**Issue by AllenCai12** [FelisCatus/SwitchyOmega#1905]
系统： ubuntu16.04 
我设置好所有东西（代理服务器，代理规则等）， 都会自动清空，使我每次都重新设置

SwitchyOmega 2.5.20
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```
Error: IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)
    at callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3966:19)
From previous event:
    at Object.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3960:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5871:41)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9011:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9148:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8973:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4503:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:242:13
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:482:4
```

**Comment by yfdyh000** [comment]
看上去是你的浏览器的问题。
