### ISSUE TITLE
ReferenceError: OmegaPac is not defined

### ISSUE THREAD

**Issue by cloudecho** [FelisCatus/SwitchyOmega#192]
Hello FelisCatus，按照README的步骤，安装到chrome后无法使用，日志：
ReferenceError: OmegaPac is not defined
    at Object.57 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:7215:18)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:583)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:634
    at Object.61../default_options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:7450:12)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:583)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:634
    at Object.OmegaTarget../src/browser_storage (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8775:12)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:583)
    at e (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:754)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1:772

ReferenceError: OmegaTarget is not defined
    at Object.18 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3047:18)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:591)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:642
    at Object.19.omega-target (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3053:15)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:591)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:642
    at Object.25../chrome_api (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4070:25)
    at s (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:591)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:1:642
    at Object.1../src/external_api.coffee (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5:12)

ReferenceError: OmegaTargetChromium is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:6:38
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:366:4

ReferenceError: OmegaPac is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega.js:4:55
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega.js:79:4

ReferenceError: OmegaPac is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega.js:4:55
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega.js:79:4

SwitchyOmega 2.2.13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
我感觉是 `npm link` 运行失败的关系……可以试试看这样：

```bash
    # In project root directory
    cd omega-web
    npm link omega-pac
    # Please paste the error output here in case it fails.
    cd ../omega-build
    grunt
```

然后重新加载下扩展试试看。

**Comment by FelisCatus** [comment]
我改了下 package.json ，现在应该好了？如果还不行的话就是 npm 的问题了……

**Comment by cloudecho** [comment]
可以了，果然是npm link问题：

  # In project root directory
    cd omega-web
    npm link omega-pac
    # Please paste the error output here in case it fails.
    cd ../omega-build
    grunt
