### ISSUE TITLE
"npm run deps" failed on Windows

### ISSUE THREAD

**Issue by liudonghua123** [FelisCatus/SwitchyOmega#214]
When I run "npm run deps" on Windows, it failed with the following error message.
```
E:\code\chrome_extension\SwitchyOmega\omega-build>npm run deps

> omega-build@0.0.1 deps E:\code\chrome_extension\SwitchyOmega\omega-build
> npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && npm install
&& bower install); (cd ../omega-target-chromium-extension/ && npm install);

(cd was unexpected at this time.

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deps"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE
npm ERR! omega-build@0.0.1 deps: `npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install);
(cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omega-build@0.0.1 deps script 'npm install && (cd ../omega-pac && npm install); (cd ../omega-targ
et && npm install); (cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm in
stall);'.
npm ERR! This is most likely a problem with the omega-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && n
pm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);
npm ERR! You can get their info via:
npm ERR!     npm owner ls omega-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\code\chrome_extension\SwitchyOmega\omega-build\npm-debug.log

E:\code\chrome_extension\SwitchyOmega\omega-build>
```

The detail log in file "E:\code\chrome_extension\SwitchyOmega\omega-build\npm-debug.log" is below.
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deps' ]
2 info using npm@2.2.0
3 info using node@v0.10.35
4 verbose run-script [ 'predeps', 'deps', 'postdeps' ]
5 info predeps omega-build@0.0.1
6 info deps omega-build@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info omega-build@0.0.1 Failed to exec deps script
9 verbose stack Error: omega-build@0.0.1 deps: `npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:212:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid omega-build@0.0.1
11 verbose cwd E:\code\chrome_extension\SwitchyOmega\omega-build
12 error Windows_NT 6.2.9200
13 error argv "node" "C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deps"
14 error node v0.10.35
15 error npm  v2.2.0
16 error code ELIFECYCLE
17 error omega-build@0.0.1 deps: `npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);`
17 error Exit status 1
18 error Failed at the omega-build@0.0.1 deps script 'npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);'.
18 error This is most likely a problem with the omega-build package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install); (cd ../omega-web && npm install && bower install); (cd ../omega-target-chromium-extension/ && npm install);
18 error You can get their info via:
18 error     npm owner ls omega-build
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by FelisCatus** [comment]
Thanks for the report. I'm not a pro at Windows command-line utilities, so I don't know what shell syntax should be used instead of the following bash syntax (which only works on *nix):

```bash
npm install && (cd ../omega-pac && npm install); (cd ../omega-target && npm install);
```

**Comment by FelisCatus** [comment]
Seems that `;` is not working for Windows cmd.exe. I will replace that with `&&`, which works both in Windows and *nix.

**Comment by FelisCatus** [comment]
Does windows cmd.exe allow subshells as in `(cd ../omega-pac && npm install)` (with the parentheses spawning a subshell in *nix)?

**Comment by celeron533** [comment]
windows环境下很有趣（win10）
'&&' 作为分隔符的话，powershell会报错，但是cmd完全没有问题，顺利走完。
';' 做分隔符，powershell和cmd都能过。
