### ISSUE TITLE
机场订阅的链接如何填写，谢谢

### ISSUE THREAD

**Issue by anson6562656** [FelisCatus/SwitchyOmega#2181]
SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
```
[2] Unhandled rejection:
 Error: Invalid options!
    at ChromeOptions.Options.parseOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9295:13)
    at ChromeOptions.Options.reset (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:9312:30)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:449:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:448:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
```

**Comment by huanghe2015** [comment]
机场订阅是在代理软件里填写，请参考代理软件的帮助。
