### ISSUE TITLE
Не работает SwitchyOmega

### ISSUE THREAD

**Issue by xe3a** [FelisCatus/SwitchyOmega#2336]
Перестал работать SwitchyOmega, не реагирует на прокси, как будто его нет.

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.124 YaBrowser/22.9.5.710 Yowser/2.5 Safari/537.36
```
[17] Unhandled rejection:
 Error: Cannot add condition to Profile  (undefined)
    at Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10164:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:449:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:448:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
```

**Comment by Artemeey** [comment]
Please, check active proxy client in config: chrome://settings/?search=proxy
You should see it there: Proxy SwitchyOmega

**Comment by Artemeey** [comment]
Please, check active proxy client in config: chrome://settings/?search=proxy
You should see it there: Proxy SwitchyOmega

**Comment by Artemeey** [comment]
Please, check active proxy client in config: chrome://settings/?search=proxy
You should see it there: Proxy SwitchyOmega
