### ISSUE TITLE
点扩展图标弹出菜单经常不显示情景模式，要多点几次才行

### ISSUE THREAD

**Issue by Parsee1** [FelisCatus/SwitchyOmega#2404]
已设置多个情景模式，未启动快捷切换，点扩展图标弹出菜单，正常期望是这样子的：
![image](https://github.com/FelisCatus/SwitchyOmega/assets/93113614/f23f85f1-4b32-468e-a634-f447bde83454)

但经常会变成这样：
![image](https://github.com/FelisCatus/SwitchyOmega/assets/93113614/f5acf49b-9796-45a3-8ae2-02c64b98b36e)

要多点好几次才行
开发模式报错如下：

﻿index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2
profiles.js:43 Uncaught TypeError: Cannot read properties of undefined (reading 'FixedProfile')
    at compareProfile (profiles.js:43:25)
    at Array.sort (<anonymous>)
    at addProfilesItems (profiles.js:145:8)
    at updateMenuByState (profiles.js:36:5)
    at v.ready (script.min.js:6:1395)
    at profiles.js:2:11
    at profiles.js:283:3

Opera、Chrome都有问题，Chrome比较严重，有时点十几次都不出

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```
[2] Unhandled rejection:
 Error
    (No stack trace)
```

**Comment by Mydong** [comment]
是的  我最近也是频繁出现这个问题  
然后 切换为老版本了  我发现  老版本  很稳定
https://chrome.google.com/webstore/detail/proxy-switchysharp/dpplabbmogkhghncfbfdeeokoefdjegm

**Comment by jinzhijie** [comment]
```js
profiles.js:43 
Uncaught TypeError: Cannot read properties of undefined (reading 'FixedProfile')
    at compareProfile (profiles.js:43:25)
    at Array.sort (<anonymous>)
    at addProfilesItems (profiles.js:145:8)
    at updateMenuByState (profiles.js:36:5)
    at v.ready (script.min.js:6:1395)
    at profiles.js:2:11
    at profiles.js:283:3
```

**Comment by hejun200613224** [comment]
有没有大佬去修一下，或者fork一个的。旧不维护真的很难受

**Comment by clamx4** [comment]
Try https://github.com/suziwen/ZeroOmega, where this issue is fixed.
