### ISSUE TITLE
情景模式的图标经常显示不出来

### ISSUE THREAD

**Issue by burgleaf** [FelisCatus/SwitchyOmega#2432]
设置了一个proxy和autoproxy的情景模式，单击右上角SwitchyOmega的图标这两个情景模式经常显示不出来，导致没办法切换情景模式。

右键扩展switchyomega的审查弹出内容为显示报错：
Uncaught TypeError: Cannot read properties of undefined (reading 'SwitchProfile')
    at compareProfile (profiles.js:43:25)
    at Array.sort (<anonymous>)
    at addProfilesItems (profiles.js:145:8)
    at updateMenuByState (profiles.js:36:5)
    at v.ready (script.min.js:6:1395)
    at profiles.js:2:11
    at profiles.js:283:3

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by silves-xiang** [comment]
我也遇到相同问题

**Comment by Aqr0129** [comment]
+1

**Comment by AnyWAT** [comment]
多点击一次（插件图标），不行再来一次

**Comment by clamx4** [comment]
Try https://github.com/suziwen/ZeroOmega, where this issue is fixed.
