### ISSUE TITLE
关于切换情景切换

### ISSUE THREAD

**Issue by riderda** [FelisCatus/SwitchyOmega#2435]
经常出现无法切换的情况。右上角的图标显示使用代理，但是点击图标后没有显示，只有直连和系统代理。

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
```
[3] Unhandled rejection:
 Error: Cannot add condition to Profile  (undefined)
    at Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10164:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:449:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:448:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:430:19
```

**Comment by clamx4** [comment]
How about trying https://github.com/suziwen/ZeroOmega?
