### ISSUE TITLE
“直接连接”和“系统代理”两个选项经常显示不出来

### ISSUE THREAD

**Issue by SlimFancy** [FelisCatus/SwitchyOmega#245]
“直接连接”和“系统代理”两个选项经常显示不出来。如下图所示
![2015-01-29 1 21 51](https://cloud.githubusercontent.com/assets/4530475/5952838/61c0820e-a7ba-11e4-8759-c20095e86201.png)

SwitchyOmega 2.3.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
```
[7] Unhandled rejection:
 Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13862:15)
    at Object.module.exports.exports.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13840:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13321:29
    at Object.module.exports.script (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13325:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11234:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3611:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11356:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:351:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:350:25
From previous event:
    at new Promise (chrome-extension

**Comment by FelisCatus** [comment]
Mac OS X 下 Chrome 弹出窗口显示不正常的情况，是已知的 Chrome 浏览器故障，与本项目无关。建议到 Chrome 那边反馈。
