### ISSUE TITLE
感觉没有switchysharp好用啊，为啥没匹配的规则不能直接连接呢

### ISSUE THREAD

**Issue by zhaozhi406** [FelisCatus/SwitchyOmega#246]
SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
```
[14] Unhandled rejection:
 TypeError: Cannot read property 'trim' of undefined
    at Object.module.exports.exports.AutoProxy.preprocess (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14251:18)
    at Object.module.exports.exports._profileTypes.RuleListProfile.analyze (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14179:36)
    at Object.module.exports.exports.analyze (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13718:42)
    at Object.module.exports.exports.match (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13826:21)
    at ChromeOptions.Options.matchProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11839:34)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:86:22
From previous event:
    at Function.Promise$Join (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1540:15)
    at OptionsSync.copyTo (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:12236:20)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10689:80)
    at ChromeOption

**Comment by FelisCatus** [comment]
把默认规则设置成直接连接就行了吧……
