### ISSUE TITLE
无法成为ubuntu chrome默认代理扩展

### ISSUE THREAD

**Issue by iciness** [FelisCatus/SwitchyOmega#268]
如题

SwitchyOmega 2.3.1
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
```
[2] Unhandled rejection:
 TypeError: Cannot read property 'trim' of undefined
    at Object.module.exports.exports.AutoProxy.preprocess (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14251:18)
    at Object.module.exports.exports._profileTypes.RuleListProfile.analyze (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14179:36)
    at Object.module.exports.exports.analyze (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13718:42)
    at Object.module.exports.exports.match (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13826:21)
    at ChromeOptions.Options.matchProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11839:34)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:92:22
From previous event:
    at Promise$then [as then] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2034:17)
    at ChromeTabs.actionForUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:89:26)
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4467:17)
    at ChromeT

**Comment by iciness** [comment]
清空chrome 重建data目录后正常
