### ISSUE TITLE
no error

### ISSUE THREAD

**Issue by ZhuFengdaaa** [FelisCatus/SwitchyOmega#318]
SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
```
[2] Unhandled rejection:
 TypeError: Cannot read property 'replace' of null
    at Object.module.exports.exports.requestFromUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:12505:27)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:91:37
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4676:25)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10688:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10802:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10650:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3785:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:195:13
```

**Comment by FelisCatus** [comment]
no error?
