### ISSUE TITLE
https://www.facebook.com/

### ISSUE THREAD

**Issue by Hiswify26** [FelisCatus/SwitchyOmega#322]
SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36
```
[3] Unhandled rejection:
 Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13963:15)
    at Object.module.exports.exports.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13941:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13422:29
    at Object.module.exports.script (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13426:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11259:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3994:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11381:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:357:23
From previous event:
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at Chro

**Comment by syswow** [comment]
duplication with  #318
