### ISSUE TITLE
自从使用了SwitchyOmega之后，经常会有网页加载不完全，哪怕是直接连接也这样的，很烦人的，太频繁啦，我现在打开一个网页都需要刷新好几次

### ISSUE THREAD

**Issue by copperhawthorn** [FelisCatus/SwitchyOmega#329]
SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
```
[1] Unhandled rejection:
 Error: Cannot add condition to Profile  (undefined)
    at ChromeOptions.Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11774:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:357:23
    at tryCatch1 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4984:21)
    at Promise$_callHandler [as _callHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2539:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2553:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2716:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:125:12)
    at Async$consumeFunctionBuffer (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:88:14)
    at MutationObserver.Promise$_Scheduler (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4189:17

**Comment by FelisCatus** [comment]
网络问题或代理服务器问题，与本项目无关。 SwitchyOmega 只设置选项，不涉及网络请求。
