### ISSUE TITLE
自动切换的图标真的太难看了，其他还挺好的

### ISSUE THREAD

**Issue by emailhxn** [FelisCatus/SwitchyOmega#350]
SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36
```
[1] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at Error (native)
    at PortImpl.postMessage (extensions::messaging:70:22)
    at Port.publicClass.(anonymous function) [as postMessage] (extensions::utils:93:26)
    at responseCallback (extensions::messaging:168:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:371:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:25
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4685:25)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10688:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10802:23)
    at ChromeOptions.Options (chrome-extension://padek

**Comment by FelisCatus** [comment]
见 #107.
