### ISSUE TITLE
Failed to route HTTPS proxy with auto-switch mode.

### ISSUE THREAD

**Issue by legendtang** [FelisCatus/SwitchyOmega#386]
Ver: 2.3.10

When I add a HTTPS proxy into auto-switch mode, everything work fine except that I cannot get any HTTP response. However, when I use the origin HTTPS proxy, it can be resolved though rules are not applied

**Comment by FelisCatus** [comment]
Please click on the "Export PAC" button on the auto-switch mode. You can then upload the PAC file to https://gist.github.com/ and paste the link here. The generated PAC file should be helpful to examine the situation.

A screenshot on the HTTPS proxy profile would also be appreciated. You may change or mask your proxy server host in both the PAC file and the screenshot in order to protect your privacy.

**Comment by legendtang** [comment]
@FelisCatus Unfortunately, "Export PAC" is broken for this mode only. Thus I ran into the console, and guess what?

````
RangeError: Maximum call stack size exceeded
    at noop (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js)
    at null.add_source_map (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:19192:17)
    at doit (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18497:22)
    at null.print (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18504:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:19011:23
    at doit (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18498:17)
    at null.print (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18504:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:19011:23
    at doit (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18498:17)
    at null.print (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:18504:17)
````

Every click causes a error threw out like this, which I think the error is relevant to my issue. I guess this is the way to reproduce the problem:
1. Add a proxy mode with HTTPS proxy.
2. Add an auto-switch mode and fill it with online gfwlist and the proxy mode above.

**Comment by FelisCatus** [comment]
Switch Profiles will use the credentials for a given proxy profile or PAC profile if that profile is selected. Make sure to provide the credentials in the Proxy Profile with the padlock button, and everything should be fine in Auto Switch.

If things are not working as expected and the Proxy Authentication dialog still pops up, please open a new issue with the settings backup file submitted.
