### ISSUE TITLE
开启同步后，每次电脑开机，所有的配置都还原了

### ISSUE THREAD

**Issue by yubaolee** [FelisCatus/SwitchyOmega#406]
如题：开始时开启同步功能的，重启浏览器后，所有的配置都还原了，试着把同步功能关闭了就不会？什么情况？只有我一个出现过吗？

附：我用的不是chrome原版，是基于chrome的猎豹。没有登陆造成的吗？

关键是生成的备份文件OmegaOptions .bak，每次用“从备份文件中恢复”都提示文件格式不正确

用的猎豹浏览器：5.3.93

SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.60 Safari/537.36 LBBROWSER
```
[2] Unhandled rejection:
 Error: "sync" is not available in this instance of Chrome
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3504:21)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:73:7)
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.clearAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at ChromeStorage.remove (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4799:27)
    at ChromeOptions.Options.resetOptionsSync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:12030:30)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:357:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:25
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBi

**Comment by FelisCatus** [comment]
猎豹浏览器怎么返回`Error: "sync" is not available in this instance of Chrome`？这真是不合常理。

我想是和配置同步有关系……猎豹浏览器那边只要试图读同步存储，就会出错，从而配置无法正常加载。这类事情还是第一次遇到……

**Comment by FelisCatus** [comment]
修复已经提交，正在等待谷歌应用商店审核通过（预计1小时以内）。

**Comment by FelisCatus** [comment]
v2.3.11 已经修复。请测试：

* 重启 SwitchyOmega 应该不会丢配置文件了。
* 但是由于猎豹浏览器并没有启用配置同步，所以不能使用配置同步。
