### ISSUE TITLE
popup window won't auto fit the content

### ISSUE THREAD

**Issue by lenonhere** [FelisCatus/SwitchyOmega#409]
![screen shot 2015-04-22 at 10 43 42](https://cloud.githubusercontent.com/assets/1567120/7266460/8656edde-e8dc-11e4-95bc-a0fc69c2286f.png)

SwitchyOmega 2.3.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
```
[1] Unhandled rejection:
 Error: Cannot add condition to Profile  (undefined)
    at ChromeOptions.Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11786:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:23
    at tryCatch1 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4984:21)
    at Promise$_callHandler [as _callHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2539:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2553:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2716:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:125:12)
    at Async$consumeFunctionBuffer (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:88:14)
    at MutationObserver.Promise$_Scheduler (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4189:17)
```

**Comment by FelisCatus** [comment]
This could be a problem with SwitchyOmega, but I suspect Chrome is doing wrong at least partially.
Based on previous reports, Chrome on OS X tend to wrongly position the popup. But this is the first report of the popup being overly large.

If possible, please try Chrome Dev channel and see if the issue can be resolved.

**Comment by lenonhere** [comment]
Did not happen in the pass few days, more info would feed back here if I find a way.

**Comment by FelisCatus** [comment]
@lenonhere Sure, thanks.
