### ISSUE TITLE
查看代理规则

### ISSUE THREAD

**Issue by yyzi** [FelisCatus/SwitchyOmega#415]
我自己添加了好多代理规则, 可是都我都看不见, 也不能编辑, 这样我都不知道哪些是代理的了, 应该让我看见

SwitchyOmega 2.3.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
```
[3] Unhandled rejection:
 Error: Cannot add condition to Profile  (undefined)
    at ChromeOptions.Options.addCondition (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11786:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:23
    at tryCatch1 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4984:21)
    at Promise$_callHandler [as _callHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2539:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2553:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2716:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:125:12)
    at Async$consumeFunctionBuffer (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:88:14)
    at MutationObserver.Promise$_Scheduler (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.mi

**Comment by FelisCatus** [comment]
代理规则可以在对应的情景模式中查看。

P.S. 如果之前使用的是临时规则，那么那些规则不会保存，也不能查看，重启后失效。
