### ISSUE TITLE
自动切换功能失效

### ISSUE THREAD

**Issue by QuantumGhost** [FelisCatus/SwitchyOmega#447]
在规则中添加了 `*.google.com`，但是使用的时候 mail.google.com 并没有被代理。

SwitchyOmega 2.3.12
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
```
[1] Unhandled rejection:
 Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14436:15)
    at Object.module.exports.exports.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:14414:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13891:29
    at Object.module.exports.script (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:13895:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11271:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4095:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11393:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:355:25
From previous event:
    at new Promise (chrome-extensio

**Comment by FelisCatus** [comment]
1. 错误信息显示自动切换或者其他地方可能使用了系统代理。虽然不知道是怎么做到的，不过最好检查下自动切换之类的设置，确保所有结果情景模式都正确选择，无空白或系统代理。
2. 此外，请截图之前说到的那条规则，以确认设置正确。
3. 如果还不行的话，请导入[样例设置备份文件](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList.bak)，然后以此为基础进行设置。

**Comment by QuantumGhost** [comment]
切换规则是这样的：
![image](https://cloud.githubusercontent.com/assets/2939865/7552987/8beef1d0-f708-11e4-8a80-40e12e3f498c.png)

同时还使用了 GFWList 作为规则列表
![image](https://cloud.githubusercontent.com/assets/2939865/7552993/e031952c-f708-11e4-8734-8d03e76fe56b.png)

确实没有看到什么有问题的地方

**Comment by FelisCatus** [comment]
@QuantumGhost 请尝试在自动切换情景模式中点击右上角“导出PAC文件”按钮，并将PAC文件上传至 https://gist.github.com/ ，并附上链接以便分析问题。导出的PAC文件中，可以适当修改或删去代理服务器地址以保护隐私。

**Comment by QuantumGhost** [comment]
https://gist.github.com/QuantumGhost/001d35f40cfb5447950c
导出的 PAC 文件

**Comment by FelisCatus** [comment]
刚才测试过，PAC文件对于`https://mail.google.com/`这个地址是使用的`SOCKS5 localhost:1080`代理。

请问使用的时候实际具体情况是怎么样的？怎么判断“mail.google.com 并没有被代理”的？会不会是页面本身可以加载，但有一些包含的资源是在其他域名下的？

**Comment by QuantumGhost** [comment]
当时的情况是，点开 SwitchyOmega，在未代理资源里面可以看到 mail.google.com
当时没有截图，现在暂时没法重现了

**Comment by FelisCatus** [comment]
那个并不是未代理资源列表，只是未加载的资源列表而已。可能加载时间过长，或者一次两次偶尔的代理失灵也会导致这种情况，别介意就好。

**Comment by QuantumGhost** [comment]
嗯，好的~
感谢您的细心解答

**Comment by QuantumGhost** [comment]
嗯，好的~
感谢您的细心解答
