### ISSUE TITLE
Where is the manual?

### ISSUE THREAD

**Issue by valtih1978** [FelisCatus/SwitchyOmega#477]
I was recomended the Switchy to make a site-specific proxy. I have set up a single proxy in profile and has make it a default in the auto-switch. It seems however, that proxy is never used. Should I restart the Chrome or what?

**Comment by FelisCatus** [comment]
There is no manual at the moment.

First, check your proxy server and configuration by selecting the proxy from the popup menu. Visit any website and see if it loads over your proxy. Sites displaying your IP address could be very helpful to tell whether you are using the proxy or not.

Next, switch to the Auto-Switch profile using the popup menu. Try loading various websites including the specific site you want to proxy.
If you have any questions regarding using rules in Switch Profile, please upload a screenshot of your Auto Switch profile.

**Comment by valtih1978** [comment]
It seems that "Apply" button is not operational. I somehow managed to set up a proxy once. The system has stuck at the proxy. It persisted using it when I asked for "Direct" access in the Switch. The only way to disable the proxy was to disable the Switchy plugin in the Chrome->Extensions. The proxy also disappeared after I have removed it from the list of proxies. But, I cannot re-create the proxy now. The Apply button in the switch stays unresponsive. I apply the old new proxy to Default again but Chrome keeps using direct connection instead.

**Comment by FelisCatus** [comment]
Could you please use the "Report issues" item in the popup menu of the icon after your click on the "Apply" button? It automatically gathers error report that is essential for locating the problem and fills that in a new Github issue. However, you don't really need to submit another issue, please just copy the report and paste in the comment area below.

**Comment by valtih1978** [comment]
I do not see any pop up over the Apply button.

**Comment by valtih1978** [comment]
I do not see anything meaningful in the Report Issues


SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
Oops. Seems that the error log isn't attached in the report. But why? I don't know.

Just be sure, did you click on the menu AFTER you clicked on the "Apply" button and found it not working? Logs are cleared upon browser restart, so maybe you need to reproduce the problem to get them. Maybe you can try the "Error log" menu item to get a full error log which you can upload to https://gist.github.com , but this only works after you reproduce the problem, too.

**Comment by valtih1978** [comment]
It seems that Error Log behaved differently this time but I do not see any error either

Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]
Options << Options#patch [
    {
        "+auto switch": {
            "revision": [
                "14d8fb668f5",
                "14d91d9ffc4"
            ]
        }
    }
]

**Comment by valtih1978** [comment]
I have noticed that I can enforce my proxy when selecting it from the Switcy drop-down list in the Chrome Extensions Bar. This may be enough for me. But, selecting auto-switch with default set to my proxy still ignores my proxy.

**Comment by valtih1978** [comment]
No, it stopped working even in forced mode.

```
Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]
Options << Options#patch [
    {
        "+auto switch": {
            "revision": [
                "14d8fb668f5",
                "14d91d9ffc4"
            ]
        }
    }
]
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "auto switch",
        "starman"
    ]
]
Options << Options#applyProfile [
    "starman"
]
Options << Options#updateProfile [
    [
        "starman"
    ]
]
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "auto switch",
        "starman"
    ]
]
Options << Options#applyProfile [
    "starman"
]
Options << Options#updateProfile [
    [
        "starman"
    ]
]
Options << Options#applyProfile [
    "system"
]
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#updateProfile [
    [
        "system"
    ]
]
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "auto switch",
        "starman"
    ]
]
Options << Options#addTempRule [
    "google.ee",
    "starman"
]
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "",
        "auto switch",
        "starman"
    ]
]
Options << Options#patch [
    {
        "+stv": [
            {
                "profileType": "FixedProfile",
                "name": "stv",
                "bypassList": [
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "<local>"
                    }
                ],
                "color": "#47b",
                "revision": "14d91f7e6db",
                "fallbackProxy": {
                    "scheme": "http",
                    "port": 8080,
                    "host": "cache.infonet.ee"
                }
            }
        ]
    }
]
Options << Options#patch [
    {
        "+auto switch": {
            "defaultProfileName": [
                "starman",
                "stv"
            ],
            "revision": [
                "14d91d9ffc4",
                "14d91f87116"
            ]
        }
    }
]
Options << Options#applyProfile [
    "auto switch",
    {
        "update": false
    }
]
Options << Options#applyProfile [
    "stv"
]
Options << Options#updateProfile [
    [
        "",
        "stv",
        "starman"
    ]
]
Options << Options#patch [
    {
        "+localhost": [
            {
                "profileType": "FixedProfile",
                "name": "localhost",
                "bypassList": [
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "<local>"
                    }
                ],
                "color": "#d497ee",
                "revision": "14d91f99400",
                "fallbackProxy": {
                    "scheme": "http",
                    "port": 80,
                    "host": "127.0.0.1"
                }
            }
        ]
    }
]
Options << Options#applyProfile [
    "localhost"
]
Options << Options#updateProfile [
    [
        "",
        "localhost",
        "starman"
    ]
]
Options << Options#applyProfile [
    "starman"
]
Options << Options#updateProfile [
    [
        "",
        "starman"
    ]
]
Options << Options#applyProfile [
    "system"
]
ERROR: applyProfile ==> Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10692:15)
    at Object.module.exports.exports.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10670:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10147:29
    at Object.module.exports.script (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10151:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11271:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4095:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11393:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:355:25
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4789:25)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10688:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10814:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10650:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3886:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:194:13
ERROR: [1] Unhandled rejection:
 Error: SystemProfile cannot be used in PAC scripts
    at Object.module.exports.exports._profileTypes.SystemProfile.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10692:15)
    at Object.module.exports.exports.compile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10670:45)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10147:29
    at Object.module.exports.script (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10151:9)
    at ChromeOptions.Options.pacForProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11271:33)
    at ChromeOptions.applyProfileProxy (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4095:27)
    at ChromeOptions.Options.applyProfile (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:11393:25)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:356:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:355:25
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3497:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4789:25)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10688:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10814:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10650:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3886:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:194:13
Options << Options#applyProfile [
    "starman"
]
Options << Options#updateProfile [
    [
        "",
        "starman"
    ]
]
```

I expect everything to hang when I choose the localhost or starman cache. But my public ip seems to stuck at 84.52.43.81 regardless of proxy I select and connection never hangs so I expect that direct connection is always used instead of proxy.

**Comment by FelisCatus** [comment]
Apparently you have a profile with empty name (i.e. `""`) and it causes problems, but I have no idea why this is even possible, with non-empty check enforced in the "New Profile" dialog. So it might be something in the code that have corrupted your options.

Could you export the settings backup file from Options > Import/Export > Settings > Make backup? A backup file would be perfect for reproducing and fixing the problem. You may change the proxy ip to `127.0.0.1` before exporting to protect your privacy.

After that, starting with fresh new options is generally recommended. You can copy the content in the following block and save it as a text file. Importing the resulting file can give you a fresh start with the initial options.

```
{"+auto switch":{"color":"#99dd99","defaultProfileName":"direct","name":"auto switch","profileType":"SwitchProfile","rules":[{"condition":{"conditionType":"HostWildcardCondition","pattern":"internal.example.com"},"profileName":"direct"},{"condition":{"conditionType":"HostWildcardCondition","pattern":"*.example.com"},"profileName":"proxy"}]},"+proxy":{"bypassList":[{"conditionType":"BypassCondition","pattern":"<local>"}],"color":"#99ccee","fallbackProxy":{"host":"proxy.example.com","port":8080,"scheme":"http"},"name":"proxy","profileType":"FixedProfile"},"-confirmDeletion":true,"-downloadInterval":1440,"-enableQuickSwitch":false,"-quickSwitchProfiles":[],"-refreshOnProfileChange":true,"-revertProxyChanges":true,"-showInspectMenu":true,"-startupProfileName":"","schemaVersion":2,"-monitorWebRequests":true}
```

**Comment by valtih1978** [comment]
Yes, this fixed everything.
