### ISSUE TITLE
设置页面全是乱码，按钮全部消失。

### ISSUE THREAD

**Issue by imswing** [FelisCatus/SwitchyOmega#485]
类似这种： {{('options_profileSyncDisabled_' + profile.syncError.reason) | tr}}

SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by FelisCatus** [comment]
麻烦在选项网页上打开一下F12开发者工具，并将Console选项卡中的错误信息复制到这里。

**Comment by imswing** [comment]
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".

    at eval (native)
    at Function.n.extend.globalEval (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:2538)
    at n.fn.extend.domManip (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:17228)
    at n.fn.extend.append (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:14886)
    at null.<anonymous> (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:16246)
    at n.access (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:30124)
    at n.fn.extend.html (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:15917)
    at e [as html] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:25:207)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular-ui-router/angular-ui-router.js:3891:18
    at J (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:54:373) <main ui-view="" class="col-lg-10 col-sm-9 col-lg-offset-2 col-sm-offset-3 angular-animate ng-scope">

**Comment by FelisCatus** [comment]
我比较怀疑这个是和其他扩展冲突导致的结果。请试试看禁用其他所有扩展后再进入 SwitchyOmega 选项页面。

如果还不行，可以打开 chrome://plugins 检查一下那边是否有什么插件引发冲突。

**Comment by gaoyan1234** [comment]
你好  乱码的问题解决了吗？

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
