### ISSUE TITLE
添加虚情景模式并保存后的操作出现爆栈

### ISSUE THREAD

**Issue by legendtang** [FelisCatus/SwitchyOmega#658]
添加虚情景模式并保存后的操作出现爆栈，原模式是一个基于列表的非 PAC 自动代理规则。无法删除

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
```
[2] Unhandled rejection:
 RangeError: Maximum call stack size exceeded
    at Object.module.exports.exports._handler (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10675:21)
    at Object.module.exports.exports.isInclusive (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10500:22)
    at Object.module.exports.exports.directReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10558:18)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10604:23)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10607:17)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10607:17)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10607:17)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:10607:17)
    at Object.module.exports.exports.allReferenceSet (chrome-extension://padekgcemlokbadohgkifijomclgjg

**Comment by FelisCatus** [comment]
这像是循环引用问题，请在选项>导入/导出中将设置备份为文件，并上传到这里，我会看看是什么问题，如何解决。

另外，以目前的情况来看，你本地的选项已经损坏（或者处在不一致的状态），建议你导出一份备份以供重现问题之后，直接导入一份 SwitchyOmega 选项（比如[这个](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList.bak)）覆盖，以免发生更多问题。

如果能告知从初始状态（或者导入以上备份文件）的情况下，怎样操作可以重现该问题就更好了，多谢。

**Comment by legendtang** [comment]
刚刚不小心删掉了损坏的备份文件。
说一下重现方式吧，模仿一个使用 AutoProxy 规则（这个规则很长，不需要说明是哪个了）的自动代理模式，然后建立虚情景模式并取代这个情景模式。

如果以上方式不能重现，请频繁取代其他情景模式和这个情景模式。

我重现了的话会上传

**Comment by legendtang** [comment]
Uploaded

**Comment by FelisCatus** [comment]
可能是替换过程中又进行了一次替换，导致了不一致吧……可能是操作进行中没有禁用，或者操作成功到刷新之间还有一段时间。等我有空去检查一下。

至于你现在这个选项的情况，在导出的文件中搜索`VirtualProfile`，然后把`defaultProfileName`后面的`"SS Auto"`（或者其他循环引用的情景模式名称）改成`"direct"`，然后再导入应该就可以修好。作为一个暂时的解决方案吧。
