### ISSUE TITLE
fail to connect proxy server

### ISSUE THREAD

**Issue by happyqiaomai** [FelisCatus/SwitchyOmega#740]
I use the same setting as switchsharp but it reported fail to connect proxy error.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
```
[1] Unhandled rejection:
 TypeError: Cannot read property 'replace' of null
    at Object.module.exports.exports.requestFromUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:9760:27)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:91:37
From previous event:
    at ChromeTabs.actionForUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:89:26)
    at ChromeTabs.processTab (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5535:17)
    at ChromeTabs.onUpdated (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5507:17)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5488:26
    at Array.forEach (native)
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5485:21)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
```

**Comment by FelisCatus** [comment]
What settings are you using then? Please at least give a screenshot of your previous settings (the proxy section) and then another screenshot of the Proxy Profile on SwitchyOmega.

You may mask or replace a few characters in your proxy host to protect your privacy. Don't mask the protocol and other settings though.

**Comment by FelisCatus** [comment]
Any updates?

**Comment by happyqiaomai** [comment]
Thanks for your concerns. Now it works successfully. Maybe the proxy collapsed at that time.
