### ISSUE TITLE
CloudFront CDN不接受代理

### ISSUE THREAD

**Issue by ghosrt** [FelisCatus/SwitchyOmega#743]
已经确认将CloudFront CDN域名加入代理列表
规则：
  *.cloudflare.net +Shadowsocks
仍然提示加载失败

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
```
[4] Unhandled rejection:
 Error: Attempting to use a disconnected port object
    at Error (native)
    at PortImpl.postMessage (extensions::messaging:65:22)
    at Port.publicClass.(anonymous function) [as postMessage] (extensions::utils:94:26)
    at responseCallback (extensions::messaging:163:16)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:373:16
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:364:15
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:345:19
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at messageListener (extensions::messaging:189:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(a

**Comment by celeron533** [comment]
有没有可能是 #557 ？
有没有尝试过不使用SO，将系统代理指向SS后进行连接？

**Comment by FelisCatus** [comment]
检查：

  * 是否选中了自动切换模式？
  * 访问的网址是什么？
    + 根据您的描述，您想访问的是 CloudFront CDN， 但规则里却是 `cloudflare`？不像是同一个网站。
  * 是否安装了其他可能冲突的扩展？比如其他代理设置扩展或者去广告扩展等。

**Comment by ghosrt** [comment]
@FelisCatus
1. 工作模式是自动切换模式确认无误
2. 访问地址：http://selio.me 
3. 关于描述中的代理规则：不好意思，问题描述里面写错了，当时看的是CDN的规则分组，CloudFront的规则如下：
`*.cloudfront.net +Shadowsocks`
4. 没有其他类似或可能影响代理设置的扩展处于运作中。

@celeron533 
刚刚测试了一下Chrome直连Shadowsocks连接的方法。
在PAC模式下，CloudFront资源会加载失败。
在全局模式下能够加载。

附加一个当时没有发现的细节：
在将当前访问的域名也加入代理范围后，CloudFront资源可以正常加载。

**Comment by FelisCatus** [comment]
请直接在新标签页中打开 cloudfront.net 网址下的那个资源（图片或脚本），看是否能够正常访问。打开开发者工具(F12)的网络请求(Network)功能然后再刷新页面，可以很方便地查看各种资源的 URL 以及加载是否成功。
无论是否能正常访问，请注意此时图标的颜色。鼠标悬停在图标上可以查看使用的代理，以及匹配的相关规则，可能有助于分析问题。

顺便说一下，我这里加上`*.cloudfront.net` 这条规则访问`http://selio.me`，并没有办法重现此问题……

**Comment by FelisCatus** [comment]
一个月了呢……我准备先关闭这个了，如果有空的话可以麻烦您按照上面的说明定位一下问题好了。有什么新的信息的话请重新开启。
