### ISSUE TITLE
关于添加条件选项和检查网页元素消失的问题

### ISSUE THREAD

**Issue by MinamiyaSion** [FelisCatus/SwitchyOmega#908]
请问下网页上点小图标添加条件选项 网页右键的检查网页元素选项 网页未加载资源显示 这几个功能是不是被删除了?还是出现什么错误没显示出来

SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
```
[1] Unhandled rejection:
 ReferenceError: Url is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4958:41
From previous event:
    at ChromeOptions.getPageInfo (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4935:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:359:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:358:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:345:19
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:151:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:151:26)
    at messageListener (extensions::messaging:207:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClas

**Comment by Hentioe** [comment]
+1，我是这样做的：
在 release 页面下载 2.3.19 版本，是正常的。虽然不是解决手段但是能临时正常使用。
估计是代码 BUG 。等待修复吧。

**Comment by mchome** [comment]
添加条件选项没了，class有ng-hide :unamused:

**Comment by bubble2016** [comment]
是的，这个很痛苦，这个功能我很常用。

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。

**Comment by moerfutin** [comment]
![omega](https://cloud.githubusercontent.com/assets/9960618/19731240/60e8bb48-9bcf-11e6-8ebd-db8678376490.PNG)

请求修复这个啊，自定义条目添加多了，就这个提示

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。

**Comment by bubble2016** [comment]
好的，我已经转发

**Comment by huzi1990** [comment]
@FelisCatus 升级2.3.1后还是不出现添加条件按钮

**Comment by FelisCatus** [comment]
@huzi1990 此功能只在使用自动切换时有效，且只能在网页上使用，在新标签页、本地文件、设置页面等场合不显示。请访问任意网站，等待网站加载完毕后再点击菜单，查看是否出现选项。

如果这样还不显示，请右键点击图标并选择反馈问题。那个功能会自动附上错误日志以供分析。
