### ISSUE TITLE
想要临时对某个域名切换规则，居然找不到按钮了，自动代理下面就是选项了，原来是有个可以选择的地方的

### ISSUE THREAD

**Issue by zhenhappy** [FelisCatus/SwitchyOmega#911]
SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2896.3 Safari/537.36
```
[4] Unhandled rejection:
 ReferenceError: Url is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4958:41
From previous event:
    at ChromeOptions.getPageInfo (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4935:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:359:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:358:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:345:19
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:151:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:151:26)
    at messageListener (extensions::messaging:196:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.pu

**Comment by nathanzeng** [comment]
同样的问题+1

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2837.0 Safari/537.36

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908.

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。

**Comment by zhenhappy** [comment]
没关系，不是故意删除功能就放心了
