### ISSUE TITLE
不能快速切换网址代理模式

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [FelisCatus/SwitchyOmega#912]
![image](https://cloud.githubusercontent.com/assets/14048129/19731958/c149034c-9bd1-11e6-8fa7-716b6821cef3.png)

在主选单下的切换按钮组消失，在“加载失败的资源列表”中亦不能规定代理模式

![image](https://cloud.githubusercontent.com/assets/14048129/19732021/fce5bd28-9bd1-11e6-8d0e-fe3ee99338c6.png)

当前使用的切换条件已经确定为自动切换

SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
```
[6] Unhandled rejection:
 ReferenceError: Url is not defined
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4958:41
From previous event:
    at ChromeOptions.getPageInfo (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4935:20)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:359:23
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:358:35
From previous event:
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:345:19
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at messageListener (extensions::messaging:189:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous func

**Comment by nathanzeng** [comment]
我的今天开始也是这个样子了 重新安装之后也不行

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2837.0 Safari/537.36

**Comment by FelisCatus** [comment]
已经确认的 bug ，新版本已经提交审核。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908.

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。
