### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by dan-me** [FelisCatus/SwitchyOmega#933]
导入OmegaOptions.bak 提示 备份文件格式错误！ 手动添加情景模式保存后，重启浏览器后配置信息消失了。 

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
```
Error: IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)
    at Object.callback (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3925:21)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
From previous event:
    at StorageArea.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3918:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:5247:25)
    at ChromeOptions.Options.loadOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8795:32)
    at ChromeOptions.Options.init (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8921:23)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:8757:12)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4305:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:197:13
    at chrome-extension://padekgcemlokba

**Comment by FelisCatus** [comment]
哈？这……错误……完全没见过，而且也不是 SwitchyOmega 产生的。

我个人感觉很可能是 Chrome 的用户资料文件处在只读文件系统上（ e.g. 光盘、有些带写保护的 U 盘），或者是文件系统的权限设置禁止 Chrome 写入任何文件。总之姑且试试看重装 Chrome 或者更换用户资料文件夹的位置吧……

**Comment by FelisCatus** [comment]
顺便，如果是自定义的 Chrome 版本（例如360极速浏览器）或者启用了特殊的设置也请说明。

**Comment by dan-me** [comment]
@FelisCatus  现在好了，可能是浏览器问题

**Comment by FelisCatus** [comment]
暂时先关闭了……
