### ISSUE TITLE
ceshi

### ISSUE THREAD

**Issue by suyilearn** [FelisCatus/SwitchyOmega#939]
SwitchyOmega 2.2.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
```
[1] Unhandled rejection:
 Error: Invalid options!
    at ChromeOptions.Options.reset (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10502:29)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:339:23
    at tryCatch1 (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4984:21)
    at Promise$_callHandler [as _callHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2539:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2553:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:2716:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:125:12)
    at Async$consumeFunctionBuffer (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:88:14)
    at MutationObserver.Promise$_Scheduler (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:4189:17)
```

**Comment by FelisCatus** [comment]
???
